name: Validate projects.json
on: pull_request
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install ajv-cli
      - name: Validate projects.json
        run: ./validate.sh projects.json
